
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>



development:
  <<: *default
  database: post_publisher_development

test:
  <<: *default
  database: post_publisher_test


production:
  primary: &primary_production
    <<: *default
    database: post_publisher
    username: post_publisher
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>